# Generated by Django 5.0.1 on 2026-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('intent', models.CharField(choices=[('buy_bike', 'Buy Bike'), ('buy_part', 'Buy Spare Part'), ('service', 'Book Service'), ('finance', 'Finance')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=80)),
                ('event_id', models.CharField(blank=True, max_length=120)),
                ('page_url', models.URLField(blank=True, max_length=800)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fbp', models.CharField(blank=True, max_length=220)),
                ('fbc', models.CharField(blank=True, max_length=220)),
                ('gclid', models.CharField(blank=True, max_length=220)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_type', models.CharField(choices=[('bike', 'Bike'), ('spare_part', 'Spare Part')], max_length=20)),
                ('category', models.CharField(max_length=80)),
                ('brand', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('limited', 'Limited'), ('preorder', 'Preorder')], default='in_stock', max_length=20)),
                ('image_url', models.URLField(max_length=600)),
                ('power_score', models.PositiveSmallIntegerField(default=80)),
                ('short_description', models.CharField(max_length=240)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('tier', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=260)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
