# Generated by Django 5.0 on 2026-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.JSONField(blank=True, default=list, help_text='List of available color names'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_bikes',
            field=models.JSONField(blank=True, default=list, help_text='List of compatible bike models'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_cc',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Engine displacement in cc', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fitment_note',
            field=models.CharField(blank=True, help_text='Installation note or fitment guide', max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_capacity_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='max_power',
            field=models.CharField(blank=True, help_text='e.g. 43 bhp @ 9000 rpm', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='max_torque',
            field=models.CharField(blank=True, help_text='e.g. 44 Nm @ 7000 rpm', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage_kmpl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='seat_height_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='transmission',
            field=models.CharField(blank=True, help_text='e.g. 6-speed manual', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Kerb weight in kg', null=True),
        ),
    ]
