# Generated by Django 5.0.1 on 2026-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='intent',
            field=models.CharField(choices=[('buy_bike', 'Buy Bike'), ('buy_part', 'Buy Spare Part'), ('service', 'Book Service'), ('finance', 'Finance'), ('general', 'General Enquiry')], max_length=30),
        ),
    ]
