# Generated by Django 5.0.1 on 2026-05-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_add_product_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lyricz Motors Exclusive', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Ride the Future', max_length=240)),
                ('meta_description', models.CharField(blank=True, default='Premium bikes, performance spare parts, and service center bookings.', max_length=400)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL — used if no file uploaded', max_length=600)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon_url', models.URLField(blank=True, help_text='External favicon URL — used if no file uploaded', max_length=600)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('og_image_url', models.URLField(blank=True, max_length=600)),
                ('phone', models.CharField(blank=True, default='+880 17XX-XXXXXX', max_length=40)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number (digits only, with country code)', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=240)),
                ('facebook_url', models.URLField(blank=True, max_length=400)),
                ('instagram_url', models.URLField(blank=True, max_length=400)),
                ('youtube_url', models.URLField(blank=True, max_length=400)),
                ('tiktok_url', models.URLField(blank=True, max_length=400)),
                ('twitter_url', models.URLField(blank=True, max_length=400)),
                ('copyright_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
