# Generated by Django 5.0 on 2026-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_add_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modification/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used if no file uploaded)', max_length=600)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed URL or direct video link', max_length=600)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modification Gallery Item',
                'verbose_name_plural': 'Modification Gallery',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModificationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('tag', models.CharField(blank=True, help_text='e.g. Most Popular, Premium', max_length=60)),
                ('price_display', models.CharField(help_text='e.g. 8,500 or 25,000+', max_length=40)),
                ('duration', models.CharField(help_text='e.g. 1 day, Half day', max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('perks', models.JSONField(blank=True, default=list, help_text='List of perk strings')),
                ('accent_color', models.CharField(blank=True, default='volt', help_text='Accent colour key: volt | ignition | boost | slate', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modification Service',
                'verbose_name_plural': 'Modification Services',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
