# Generated by Django 5.0 on 2026-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_modificationgallery_modificationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=2200&q=85', help_text='Hero background image URL (used when media type = Image)', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'YouTube / Video')], default='image', help_text='Image shows a static background; Video embeds a YouTube autoplay loop.', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://youtu.be/XXXX or watch?v=). Autoplay muted loop on homepage hero.', max_length=600),
        ),
    ]
