# Generated by Django 5.0 on 2026-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_sitesettings_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='modification_hero_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=2000&q=85', help_text='Modification page hero background image URL', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modification_hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'YouTube / Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modification_hero_video_url',
            field=models.URLField(blank=True, help_text='YouTube URL for modification page hero video (autoplay muted loop)', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_hero_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=2000&q=85', help_text='Service page hero background image URL', max_length=600),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'YouTube / Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_hero_video_url',
            field=models.URLField(blank=True, help_text='YouTube URL for service page hero video (autoplay muted loop)', max_length=600),
        ),
    ]
