# Generated by Django 5.0 on 2026-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_sitesettings_modification_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude from Google Maps (e.g. 23.7806)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude from Google Maps (e.g. 90.4193)', max_digits=10, null=True),
        ),
    ]
