# Generated by Django 5.0 on 2026-05-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_sitesettings_map_lat_sitesettings_map_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='intent',
            field=models.CharField(choices=[('buy_bike', 'Buy Bike'), ('buy_part', 'Buy Spare Part'), ('service', 'Book Service'), ('home_service', 'Home Service'), ('finance', 'Finance'), ('general', 'General Enquiry')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image file (takes priority over URL)', null=True, upload_to='products/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (used when no file uploaded)', max_length=600)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='commerce.product')),
            ],
            options={
                'verbose_name': 'Product Gallery Image',
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
