# Generated by Django 5.0.1 on 2026-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_productimage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, help_text='Rich HTML content — shown on product details page below specs.'),
        ),
    ]
